### ISSUE TITLE
Error while generating the video 

### ISSUE THREAD

**Issue by ne1114** [uwdb/visualroad#11]
Hello, first of all thank you for your amazing work.
I have been trying to generate some visualroad data following the steps listed in github. 
However, while running the 'docker-compose run generator --scale 1 my-dataset' command I am facing some issues. 

FULL OUTPUT OF ue4-docker info :
```
ue4-docker version:         0.0.62 (latest available version is 0.0.62)
Operating system:           Linux (Ubuntu 18.04.4 LTS, 5.3.0-46-generic)
Docker daemon version:      19.03.8
NVIDIA Docker supported:    No
Maximum image size:         No limit detected
Available disk space:       99.22 GiB
Total system memory:        15.59 GiB physical, 2 GiB virtual
Number of processors:       4 physical, 8 logical
```

FULL OUTPUT OF  docker-compose run generator --scale 1 my-dataset
```
error: XDG_RUNTIME_DIR not set in the environment.
Signal 11 caught.
Malloc Size=65538 LargeMemoryPoolOffset=65554
Malloc Size=65535 LargeMemoryPoolOffset=131119
Malloc Size=48848 LargeMemoryPoolOffset=179984
4.22.0-0+++UE4+Release-4.22 517 0
Disabling core dumps.
CommonUnixCrashHandler: Signal=11
Engine crash handling finished; re-raising signal 11 for the default handler. Good bye.
INFO:root:Map: Town03, Weather: WeatherParameters(cloudyness=80.000000, precipitation=60.000000, precipitation_deposits=100.000000, wind_intensity=1.000000, sun_azimuth_angle=0.000000, sun_altitude_angle=15.000000), Vehicles: 200, Walkers: 250
Traceback (most recent call last):
  File "./generator.py", line 425, in <module>
    generate(args.path, tile_pool, args.scale, (args.width, args.height), args.duration, args.fov, args.seed, args.vehicles, args.pedestrians)
  File "./generator.py", line 349, in generate
    generate_tile(client, path, id, used_tiles[-1], scale, resolution, duration, panorama_fov)
  File "./generator.py", line 232, in generate_tile
    client.load_world(tile.map)
RuntimeError: time-out of 30000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:2000
```
Would there be any suggestions on how to fix this issue, please?
Best regards.

**Comment by BrandonHaynes** [comment]
Hi Jeonghoon -- instead of robustly checking to see if Unreal has launched, I was lazy and just sleep for 20 seconds.  There's a good chance that on your hardware this isn't long enough to complete the startup process.

To confirm this hypothesis, could you please change [line 72 of `common.py`](https://github.com/uwdb/visualroad/blob/master/common.py#L72) to increase the sleep time?  E.g., give it 360 seconds just to be sure that the Unreal engine has fully launched.

Thanks!

**Comment by ne1114** [comment]
First of all thank you for a quick reply. I wasn't able to test it out for a while.

Unfortunately increasing sleep time hasn't solved the problem. I am currently using the server, and I think "_error: XDG_RUNTIME_DIR not set in the environment._" looks suspicious. 

Do you have any suggestions that could be related to the above error message please?

Thank you so much!

**Comment by BrandonHaynes** [comment]
`XDG_RUNTIME_DIR` is a normal log entry, and your output looks largely like mine.

Let's try separating the Unreal launch from the simulation.  Start a new container and run bash as follows:
```bash
docker-compose run --entrypoint bash generator
```

Then launch Unreal:
```bash
$CARLA_EXECUTABLE -benchmark -fps=30 -quality-level=Epic &
```

Wait awhile (>10 minutes) and then try running the simulator:
```bash
./generator.py test
```

**Comment by ne1114** [comment]
Unfortunately _'$CARLA_EXECUTABLE -benchmark -fps=30 -quality-level=Epic '_  didn't start the Carla. Whereas it threw segmentation fault. 
Currently, I am using CUDA10.2 build for the ue4 engine. Could that potentially be problematic?

**Comment by ne1114** [comment]
Good afternoon @BrandonHaynes. Searching for reasons why Carla isn't running, I realized that I haven't installed the nvidia-docker. After installing nvidia-docker version 2.0 I was able to run carla and successfully generated videos using default settings. 
Thank you so much for your kind help!

**Comment by BrandonHaynes** [comment]
Thanks for letting me know!  I've updated the README to reflect this dependency.
