### ISSUE TITLE
latest package opencv-python error: ModuleNotFoundError: No module named 'skbuild'

### ISSUE THREAD

**Issue by yangyueren** [uwdb/visualroad#14]
https://github.com/uwdb/visualroad/blob/dd6c20d285e01ca21fa683bd5473182c7a4abd5a/Dockerfile#L74
https://github.com/uwdb/visualroad/blob/dd6c20d285e01ca21fa683bd5473182c7a4abd5a/Dockerfile#L75

change L74 and L75 to:
`RUN pip2 install --user pyyaml opencv-python==4.0.1.24 psutil & \
    pip3 install --user pyyaml opencv-python==4.0.1.24 psutil`

Due to the following error in the latest package opevcv-python
https://pypi.org/project/opencv-python/

**Comment by BrandonHaynes** [comment]
Fixed in d381644971b616f9e09222931a866fd2772bd24a.  Thanks!
