### ISSUE TITLE
Question about ue4-docker version and build parameters

### ISSUE THREAD

**Issue by arruda** [uwdb/visualroad#3]
Hello, I just found out this great project, but I noticed that it doesn't specify which version of the ue4-docker Python package it is using, neither what configuration was used to generate the image `adamrehn/ue4-engine:4.22.0` that you are using in your Dockerfile.

I would guest that this is the ue4-engine only image (https://adamrehn.com/docs/ue4-docker/building-images/available-container-images#ue4-engine) build with CUDA instead of OpenGL (I noticed that  the nvidia runtime is specified in the dockerfile), is this correct?
And if using CUDA, what was the version used? 

Sorry for all the questions, and thank you for this great work.

**Comment by BrandonHaynes** [comment]
Hi Felipe -- these are great questions and should have been outlined in the build prerequisites.  I built the `adamrehn/ue4-engine:4.22.0` image using `ue4-docker` version [0.0.34](https://github.com/adamrehn/ue4-docker/tree/v0.0.34).  I believe that I used CUDA version 9.2, and so the build command would have looked something like this:

```sh
ue4-docker build --cuda=9.2 --pull-prerequisites --no-minimal --no-full --exclude=debug --exclude=templates 4.22.0
```

I'm actually not *positive* that this is the command line I used, but I'm rebuilding the images to confirm.  I'll add some additional detail to the README to cover this -- thanks a bunch for letting me know that I overlooked this.  And please reopen if you run into any other details that I've omitted.

**Comment by arruda** [comment]
Thanks =D
